# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  terraform-plan:
    docker:
      - image: cimg/azure:2023.03
    steps:
      - checkout
      - terraform/init:
          path: terraform
      - terraform/plan:
          path: terraform

  terraform-apply:
    docker:
      - image: cimg/azure:2023.03
    steps:
      - checkout
      - terraform/init:
          path: terraform
      - terraform/apply:
          path: terraform

  terraform-destroy-foundry:
    docker:
      - image: cimg/azure:2023.03
    steps:
      - checkout
      - terraform/init:
          path: terraform
      - run: rm terraform/foundry.tf
      - terraform/apply:
          path: terraform

workflows:
  version: 2
  terraform-plan-and-apply:
    jobs:
      - terraform-plan
      - hold: 
          type: approval 
          requires: 
           - terraform-plan
      - terraform-apply:
          requires:
            - hold
  terraform-destroy-foundry:
    jobs:
      - hold: 
          type: approval 
      - terraform-destroy-foundry:
          requires:
            - hold

